webtalk_init -webtalk_dir C:/Users/watsongd/Desktop/DigitalDesign/Lab05/Lab05/Lab05.sim/sim_1/behav/xsim.dir/preamble_shreg_bench_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Oct 22 13:12:57 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2016.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1577090" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "de267aa2-0527-46a6-acfa-3e693a1944e6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "616e6eddad524370b3d5cc18a73643a0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3600 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10001 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.72_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "17160_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1253927603 -regid "" -xml C:/Users/watsongd/Desktop/DigitalDesign/Lab05/Lab05/Lab05.sim/sim_1/behav/xsim.dir/preamble_shreg_bench_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/watsongd/Desktop/DigitalDesign/Lab05/Lab05/Lab05.sim/sim_1/behav/xsim.dir/preamble_shreg_bench_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/watsongd/Desktop/DigitalDesign/Lab05/Lab05/Lab05.sim/sim_1/behav/xsim.dir/preamble_shreg_bench_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
