webtalk_init -webtalk_dir C:/Users/ahmadw/Desktop/ECE491/DigitalDesign/Lab03/Lab03.sim/sim_1/behav/xsim.dir/mxtest_bench_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Sep 15 17:44:03 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2016.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1577090" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "646344f8-1653-4329-909c-b92f1fe034ce" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "83f6e1599ada4e8393d091507958fa27" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "26" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3600 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10004106 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "2.20_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "17284_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3946472454 -regid "" -xml C:/Users/ahmadw/Desktop/ECE491/DigitalDesign/Lab03/Lab03.sim/sim_1/behav/xsim.dir/mxtest_bench_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/ahmadw/Desktop/ECE491/DigitalDesign/Lab03/Lab03.sim/sim_1/behav/xsim.dir/mxtest_bench_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/ahmadw/Desktop/ECE491/DigitalDesign/Lab03/Lab03.sim/sim_1/behav/xsim.dir/mxtest_bench_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
